"""empty message

Revision ID: 65e8fa73797a
Revises: f35e97bf5298
Create Date: 2023-04-27 06:04:58.316887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e8fa73797a'
down_revision = 'f35e97bf5298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunicacion', schema=None) as batch_op:
        batch_op.drop_constraint('comunicacion_tipos_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('comunicacion_users_id_fkey', type_='foreignkey')
        batch_op.drop_column('users_id')
        batch_op.drop_column('tipos_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunicacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipos_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='comment'))
        batch_op.add_column(sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('comunicacion_users_id_fkey', 'users', ['users_id'], ['id'])
        batch_op.create_foreign_key('comunicacion_tipos_id_fkey', 'tipos', ['tipos_id'], ['id'])

    # ### end Alembic commands ###
