"""empty message

Revision ID: 863974004e83
Revises: 976e83704f69
Create Date: 2023-04-27 05:47:16.988504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863974004e83'
down_revision = '976e83704f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunicacion', schema=None) as batch_op:
        batch_op.drop_constraint('comunicacion_users_id_fkey', type_='foreignkey')
        batch_op.drop_column('users_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunicacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('comunicacion_users_id_fkey', 'users', ['users_id'], ['id'])

    # ### end Alembic commands ###
