"""empty message

Revision ID: bc024b06d81d
Revises: 65e8fa73797a
Create Date: 2023-04-27 06:06:52.566977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc024b06d81d'
down_revision = '65e8fa73797a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunicacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipos_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('users_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['users_id'], ['id'])
        batch_op.create_foreign_key(None, 'tipos', ['tipos_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunicacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('users_id')
        batch_op.drop_column('tipos_id')

    # ### end Alembic commands ###
